#!/usr/bin/env bash

if [ -z "$NODE_ENV" ]; then NODE_ENV=development; fi

[ "$NODE_ENV" = production ] &&
  ORIGIN=http://www.command-art.com/ ||
  ORIGIN=http://localhost:3049/

NODE_BIN=./node_modules/.bin
DIST_PATH=dist

VERSION=`cat manifest.json | grep "\"version\"" | tr -dc '[0-9.]'`;
NAME=command-art-"$NODE_ENV"-"$VERSION"

TARGET_DIR="$DIST_PATH"/"$NAME"

rm -rf "$DIST_PATH"
mkdir -p "$TARGET_DIR"

"$NODE_BIN"/browserify page.js -t envify --outfile "$TARGET_DIR"/page.js
"$NODE_BIN"/browserify background.js -t envify --outfile "$TARGET_DIR"/background.js

cat manifest.json | sed s,ORIGIN,$ORIGIN,g > "$TARGET_DIR"/manifest.json
cp page.html "$TARGET_DIR"/page.html
cp -rf icons "$TARGET_DIR"/icons/


